### ISSUE TITLE
Error Response returns Gzip

### ISSUE THREAD

**Issue by datdevboi** [getconversio/node-bigcommerce#68]
Hi, 
All my errors come in gzipped, is there a way to handle this without an external package?
My config is using apiVersion:3.

**Comment by philspitler** [comment]
Hey @datdevboi, I'm not sure what issue you're having, but I was receiving the same sort of errors until I figured out that some calls like "store info" have to be v2 and some have to be v3.  I solved the issue and have some sample code here: https://github.com/getconversio/node-bigcommerce/issues/66#issuecomment-490114975

I hope this helps.

**Comment by datdevboi** [comment]
Hey @philspitler, I appreciate the response. The only time I am getting a gzip response is when I get an error back, otherwise any successful response is sent in json.

**Comment by meshuggie** [comment]
This is a bug. The problem is with these lines: https://github.com/getconversio/node-bigcommerce/blob/master/lib/request.js#L112

I've checked the response headers directly in that file, and they are gzip. With an error, the script simply creates a new error and sets the raw (gzipped) body to the error responseBody key, and returns the rejected error .

The script should prep the data for the response and handle gzipped accordingly, regardless if it's rejecting with an error, or returning the successful response.
