### ISSUE TITLE
Error: No default engine was specified and no extension was provided.

### ISSUE THREAD

**Issue by wangxingxing123654** [getconversio/node-bigcommerce#69]
No default engine was specified and no extension was provided.what should i do

**Comment by techloverparveen** [comment]
i am also facing the same issue

**Comment by stefanosala** [comment]
@techloverparveen can you please share a bit more details?

**Comment by techloverparveen** [comment]
> @techloverparveen can you please share a bit more details?

is there any way I can test my app (without actually publish to marketplace) by installing to my store? so that I check the authentication process, like what is coming in get request and others live?

**Comment by techloverparveen** [comment]
@stefanosala that issue was due to rendering engine, I haven't defined any template engine with my Node app.
Just wondering to know how we can render the component(HTML) of React, instead of rendering from server side, I mean is there any way we can render the HTML via react client side instead of using any template engine with nodejs app.

**Comment by stefanosala** [comment]
@techloverparveen sorry, this is out of scope of this module and beyond my knowledge :( I'd recommend asking on StackOverflow. Cheers!

**Comment by techloverparveen** [comment]
Sure @stefanosala, Let me ask over Stackoverflow. Thanks for your response :)
