### ISSUE TITLE
Api for Customers

### ISSUE THREAD

**Issue by gabselbach** [getconversio/node-bigcommerce#92]
Today the lib does not support calls to customer apis, right? 
 like GET https://api.bigcommerce.com/stores/{store_hash}/v3/customers

**Comment by Greenroads-Main** [comment]
it does? you would just use the request verb GET from the node-bigcommerce instance.

bigcommerce.get("/customers") in your case since using v3 it will be bigcommerce.get("/catalog/customers") follow bigcommerce docs for correct routes. 

**_old question, figured if anyone else needs this answered._**

**Comment by william1benn** [comment]
it does? you would just use the request verb GET from the node-bigcommerce instance.

bigcommerce.get("/customers") in your case since using v3 it will be bigcommerce.get("/catalog/customers") 
**follow bigcommerce docs for correct routes.**

old question, figured if anyone else needs this answered.

**Comment by gabselbach** [comment]
Thank you @william1benn  i resolved my problem
